---
- name: Install virtualenv
  pip: "name=virtualenv"

- name: Install python deps with virtualenv
  pip: "requirements={{ caffe_root }}/python/requirements.txt virtualenv={{ caffe_virtualenv }}"
  when: caffe_with_virtualenv

- name: Install python deps without virtualenv
  pip: "requirements={{ caffe_root }}/python/requirements.txt"
  when: not caffe_with_virtualenv

- name: Add caffe path to virtualenv
  template: "src=caffe.pth.j2 dest={{ caffe_virtualenv }}/lib/python2.7/site-packages/caffe.pth"
  when: caffe_with_virtualenv
